jwt_secret: very_difficult_key

spring:
  datasource:
    url: jdbc:postgresql://172.31.192.189:5432/jwt_security_database
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
