jwt_secret: very_difficult_key

spring:
  datasource:
    url: jdbc:postgresql://your_ip_address:5432/your_database
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
